# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Tue Aug 12 10:45:32 2014
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MultiImportResultDialogue(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MultiImportResultDialogue.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("Changed Files\n"))
        self.Changed_Files_List = wx.ListBox(self, wx.ID_ANY, choices=[], style=wx.LB_HSCROLL)
        self.OK_Changes = wx.Button(self, wx.ID_ANY, _("Ok\n"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOk, self.OK_Changes)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MultiImportResultDialogue.__set_properties
        self.SetTitle(_("dialog_2"))
        self.SetSize((567, 538))
        self.Changed_Files_List.SetMinSize((-1, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MultiImportResultDialogue.__do_layout
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_15.Add(self.label_5, 0, wx.ALL, 2)
        sizer_15.Add(self.Changed_Files_List, 0, wx.EXPAND, 0)
        sizer_15.Add(self.OK_Changes, 0, wx.ALL, 2)
        self.SetSizer(sizer_15)
        self.Layout()
        # end wxGlade

    def OnOk(self, event):  # wxGlade: MultiImportResultDialogue.<event_handler>
        self.Close()
        
# end of class MultiImportResultDialogue
