# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Sat Jun 14 18:06:39 2014
#

import wx
import utilities
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class MultiImportDialogue(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MultiImportDialogue.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.ImportDialogueHeadline = wx.StaticText(self, wx.ID_ANY, _("Select path to audio folder and loc sheet"))
		self.audioPathLabel = wx.StaticText(self, wx.ID_ANY, _("Not assigned"))
		self.audioPathButton = wx.Button(self, wx.ID_ANY, _("Select Audio Folder..."))
		self.textPathLabel = wx.StaticText(self, wx.ID_ANY, _("Not assigned"))
		self.textPathButton = wx.Button(self, wx.ID_ANY, _("Select Text Sheet..."))
		self.importButton = wx.Button(self, wx.ID_ANY, _("Import"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.OnAudioPathButton, self.audioPathButton)
		self.Bind(wx.EVT_BUTTON, self.OnTextPathButton, self.textPathButton)
		self.Bind(wx.EVT_BUTTON, self.OnImportButton, self.importButton)
		# end wxGlade

		self.mainFrame = args[0]
		self.audioPath = None
		self.textPath = None
		
	def __set_properties(self):
		# begin wxGlade: MultiImportDialogue.__set_properties
		self.SetTitle(_("Import Multiple Files..."))
		self.textPathButton.Enable(False)
		self.importButton.Enable(False)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MultiImportDialogue.__do_layout
		importDialogueSizer = wx.BoxSizer(wx.VERTICAL)
		locPathSizer = wx.BoxSizer(wx.HORIZONTAL)
		audioPathSizer = wx.BoxSizer(wx.HORIZONTAL)
		importDialogueSizer.Add(self.ImportDialogueHeadline, 0, wx.BOTTOM, 20)
		audioPathSizer.Add(self.audioPathLabel, 1, wx.LEFT, 2)
		audioPathSizer.Add(self.audioPathButton, 0, wx.ALL, 2)
		importDialogueSizer.Add(audioPathSizer, 1, wx.EXPAND, 0)
		locPathSizer.Add(self.textPathLabel, 1, wx.LEFT, 2)
		locPathSizer.Add(self.textPathButton, 0, wx.ALL, 2)
		importDialogueSizer.Add(locPathSizer, 1, wx.EXPAND, 0)
		importDialogueSizer.Add(self.importButton, 0, wx.ALL | wx.ALIGN_RIGHT, 2)
		self.SetSizer(importDialogueSizer)
		importDialogueSizer.Fit(self)
		self.Layout()
		# end wxGlade
	
	def OnAudioPathButton(self, event):	 # wxGlade: MultiImportDialogue.<event_handler>
		dlg = wx.DirDialog(
			self, message = "Select Directory to import audio files from", defaultPath	= self.mainFrame.config.Read("WorkingDir", utilities.get_main_dir()),
			style = wx.DD_DIR_MUST_EXIST)
			
		if dlg.ShowModal() == wx.ID_OK:
			self.audioPath = dlg.GetPath()
			self.audioPathLabel.SetLabel(self.audioPath)
			
			self.textPathButton.Enable(True)
			self.importButton.Enable(True)
	
	def OnTextPathButton(self, event):	# wxGlade: MultiImportDialogue.<event_handler>
		dlg = wx.FileDialog(
			self, message = "Select text file", defaultDir = self.mainFrame.config.Read("WorkingDir", utilities.get_main_dir()),
			defaultFile = "", wildcard = "TXT files (*.txt)|*.txt", style = wx.OPEN | wx.CHANGE_DIR | wx.FILE_MUST_EXIST)
			
		if dlg.ShowModal() == wx.ID_OK:
			self.textPath = dlg.GetPaths()[0]
			self.textPathLabel.SetLabel(self.textPath)
		
	def OnImportButton(self, event):  # wxGlade: MultiImportDialogue.<event_handler>
		self.mainFrame.ImportMultipleAudioFiles(self.audioPath, self.textPath)
		self.Close()
		
	# end of class MultiImportDialogue