#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Thu Jun 19 16:02:28 2014
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from LipsyncFrame import LipsyncFrame

class LipsyncApp(wx.App):
    def OnInit(self):
        mainFrame = LipsyncFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        return 1

# end of class LipsyncApp

if __name__ == "__main__":
    gettext.install("unigayo") # replace with the appropriate catalog name

    unigayo = LipsyncApp(0)
    unigayo.MainLoop()